<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsRoslynComponent>true</IsRoslynComponent>
		<NoWarn>$(NoWarn);IDE0130;</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<!--
		  The following project references are required only for the purpose of testing the source generator in this project.

		  In reality, reference the NuGet package:

		  <PackageReference Include="Purview.SourceGeneratorFramework" PrivateAssets="all" Version="*" />

		-->
		<ProjectReference Include="..\SourceGeneratorFramework\SourceGeneratorFramework.csproj" />
		<ProjectReference
			Include="..\SourceGeneratorFramework.Generators\SourceGeneratorFramework.Generators.csproj"
			OutputItemType="Analyzer"
			PrivateAssets="all"
			ReferenceOutputAssembly="false"
		/>
		<ProjectReference
			Include="..\SourceGeneratorFramework.Analyzers\SourceGeneratorFramework.Analyzers.csproj"
			OutputItemType="Analyzer"
			PrivateAssets="all"
			ReferenceOutputAssembly="false"
		/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" />
	</ItemGroup>

	<PropertyGroup>
		<_PurviewSourceGeneratorFrameworkAssembly>$(TargetDir)Purview.SourceGeneratorFramework.dll</_PurviewSourceGeneratorFrameworkAssembly>
		<_PurviewSourceGeneratorFrameworkMergeTool>..\SourceGeneratorFramework.MergeTool\bin\$(Configuration)\net10.0\Purview.SourceGeneratorFramework.MergeTool.dll</_PurviewSourceGeneratorFrameworkMergeTool>
		<_PurviewSourceGeneratorFrameworkMergeToolProject>..\SourceGeneratorFramework.MergeTool\SourceGeneratorFramework.MergeTool.csproj</_PurviewSourceGeneratorFrameworkMergeToolProject>
		<PurviewMergeSourceGeneratorFrameworkForAnalyzerFiles>false</PurviewMergeSourceGeneratorFrameworkForAnalyzerFiles>
	</PropertyGroup>
	<Import Project="..\SourceGeneratorFramework\Sdk\build\Purview.SourceGeneratorFramework.targets" />
</Project>
