using Microsoft.CodeAnalysis;
using Purview.SourceGeneratorFramework.Helpers;

namespace Fixture.Generator;

/// <summary>
/// Minimal incremental generator used to give the fixture component a real analyzer artifact. It
/// uses framework helpers so the unmerged component carries an assembly reference to
/// <c>Purview.SourceGeneratorFramework</c>, exactly like a real framework-based component.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class FixtureGenerator : IIncrementalGenerator
{
	/// <inheritdoc />
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var disabled = IncrementalPipeline.IsDisabledValueProvider(context, "Fixture_Disable");

		context.RegisterSourceOutput(
			disabled,
			static (output, isDisabled) =>
			{
				if (isDisabled)
					return;

				output.AddSource(
					"Fixture.Generator.Marker.g.cs",
					"// <auto-generated />\n"
						+ "namespace Fixture.Generator.Generated;\n\n"
						+ "internal static class Marker\n"
						+ "{\n"
						+ "\tinternal const string DiagnosticId = \""
						+ FixtureComponentDiagnostics.DiagnosticId
						+ "\";\n"
						+ "}\n"
				);
			}
		);
	}
}
