<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsRoslynComponent>true</IsRoslynComponent>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SourceGeneratorFramework\SourceGeneratorFramework.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" />
	</ItemGroup>

	<Target
		Name="DeclareFrameworkRuntimeDependency"
		BeforeTargets="CopySourceGeneratorRuntimeDependencies;GetSourceGeneratorAnalyzerFiles"
	>
		<ItemGroup>
			<SourceGeneratorRuntimeDependency
				Include="@(ReferenceCopyLocalPaths)"
				Condition="'%(ReferenceCopyLocalPaths.Filename)%(ReferenceCopyLocalPaths.Extension)' == 'Purview.SourceGeneratorFramework.dll'"
			>
				<DestinationSubPath>%(ReferenceCopyLocalPaths.Filename)%(ReferenceCopyLocalPaths.Extension)</DestinationSubPath>
			</SourceGeneratorRuntimeDependency>
		</ItemGroup>
	</Target>
</Project>
