<Project>
	<PropertyGroup>
		<TestingTargetFrameworks>net8.0;net9.0;net10.0;</TestingTargetFrameworks>
		<TargetFrameworks>netstandard2.1;$(TestingTargetFrameworks)</TargetFrameworks>
		<MergeToolTFM>net10.0</MergeToolTFM>
		<NamespacePrefix>Purview.SourceGeneratorFramework</NamespacePrefix>
		<ExcludePurviewTelemetry>true</ExcludePurviewTelemetry>
		<RepositoryUrl>https://github.com/purview-dev/sourcegenerator-framework</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup>
		<SourceGeneratorFrameworkRoslynInnerBuild Condition="'$(SourceGeneratorFrameworkRoslynInnerBuild)' == ''"
			>false</SourceGeneratorFrameworkRoslynInnerBuild>
		<BaseIntermediateOutputPath Condition="'$(SourceGeneratorFrameworkRoslynInnerBuild)' == 'true'"
			>obj\$(Configuration)\roslyn$(RoslynCompilerVersion)\</BaseIntermediateOutputPath>
		<BaseOutputPath Condition="'$(SourceGeneratorFrameworkRoslynInnerBuild)' == 'true'"
			>bin\$(Configuration)\roslyn$(RoslynCompilerVersion)\</BaseOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<!--
			- CA1510 is because of .NET Standard, we can't use APIs such as
				ArgumentNullException.ThrowIfNull()
		-->
		<NoWarn>$(NoWarn);CA1031;CA1510;</NoWarn>
	</PropertyGroup>

	<Import Sdk="Purview.BuildSdk" Project="Sdk.props" />

	<PropertyGroup Condition="'$(IsTestProject)' == 'true' OR '$(IsSharedTestingProject)' == 'true'">
		<!-- Test projects aren't executable so we need to remove .NET Standard 2.1 -->
		<TargetFrameworks>$(TestingTargetFrameworks)</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Label="Purview site URL metadata">
		<PurviewHomepage>https://purview.dev/</PurviewHomepage>
		<PurviewProjectUrl>$(PurviewHomepage)projects/sourcegenerator-framework/</PurviewProjectUrl>
		<PurviewDocsUrl>$(PurviewHomepage)docs/sourcegenerator-framework/</PurviewDocsUrl>
	</PropertyGroup>

	<PropertyGroup Condition="'$(IsPackable)' == 'true'">
		<Authors>Purview Contributors</Authors>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<PackageProjectUrl>$(PurviewProjectUrl)</PackageProjectUrl>
		<RepositoryUrl>https://github.com/purview-dev/sourcegenerator-framework</RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageIcon>purview-logo-light.png</PackageIcon>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup Label="NuGet package assets" Condition="'$(IsPackable)' == 'true'">
		<None Include="..\..\..\LICENSE.md" Link="Sdk\LICENSE.md" />
		<None Include="..\..\..\assets/images/purview-logo-light.png" Link="Sdk\purview-logo-light.png" />
	</ItemGroup>
</Project>
