<Project>
	<PropertyGroup>
		<TestingTargetFrameworks>net8.0;net9.0;net10.0;</TestingTargetFrameworks>
		<TargetFrameworks>netstandard2.1;$(TestingTargetFrameworks)</TargetFrameworks>
		<NamespacePrefix>Purview.SourceGeneratorFramework</NamespacePrefix>
		<ExcludePurviewTelemetry>true</ExcludePurviewTelemetry>
		<RepositoryUrl>https://github.com/purview-dev/sourcegeneratorframework</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup>
		<SourceGeneratorFrameworkRoslynInnerBuild Condition="'$(SourceGeneratorFrameworkRoslynInnerBuild)' == ''"
			>false</SourceGeneratorFrameworkRoslynInnerBuild>
		<BaseIntermediateOutputPath Condition="'$(SourceGeneratorFrameworkRoslynInnerBuild)' == 'true'"
			>obj\$(Configuration)\roslyn$(RoslynCompilerVersion)\</BaseIntermediateOutputPath>
		<BaseOutputPath Condition="'$(SourceGeneratorFrameworkRoslynInnerBuild)' == 'true'"
			>bin\$(Configuration)\roslyn$(RoslynCompilerVersion)\</BaseOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<!--
			- CA1510 is because of .NET Standard, we can't use APIs such as
				ArgumentNullException.ThrowIfNull()
		-->
		<NoWarn>$(NoWarn);CA1031;CA1510;</NoWarn>
	</PropertyGroup>

	<Import Sdk="Purview.DotNetProjectSdk" Project="Sdk.props" />

	<PropertyGroup Condition="'$(IsTestProject)' == 'true' OR '$(IsSharedTestingProject)' == 'true'">
		<!-- Test projects aren't executable so we need to remove .NET Standard 2.1 -->
		<TargetFrameworks>$(TestingTargetFrameworks)</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(IsPackable)' == 'true'">
		<Authors>Purview Contributors</Authors>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<PackageProjectUrl>https://github.com/purview-dev/sourcegeneratorframework</PackageProjectUrl>
		<RepositoryUrl>https://github.com/purview-dev/sourcegeneratorframework</RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageIcon>purview-logo.jpg</PackageIcon>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup Label="NuGet package assets" Condition="'$(IsPackable)' == 'true'">
		<None Include="..\..\..\LICENSE.md" Link="Sdk\LICENSE.md" />
		<None Include="..\..\..\assets/images/purview-logo.jpg" Link="Sdk\purview-logo.jpg" />
	</ItemGroup>
</Project>
