<Project>
	<PropertyGroup Condition="'$(IsPackable)' == 'true'">
		<Authors>Purview Contributors</Authors>
		<Description>Purview SourceGeneratorFramework libraries for building and testing incremental C# source generators.</Description>
		<PackageProjectUrl>https://github.com/purview-dev/sourcegeneratorframework</PackageProjectUrl>
		<RepositoryUrl>https://github.com/purview-dev/sourcegeneratorframework</RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>purview-logo.png</PackageIcon>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<Import Sdk="Purview.DotNetProjectSdk" Project="Sdk.targets" />
</Project>
