<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>$(MergeToolTFM)</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ILRepack.Lib" />
		<PackageReference Include="Mono.Cecil" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Purview.SourceGeneratorFramework.MergeTool.UnitTests" />
	</ItemGroup>
</Project>
